CREATE TABLE "conversation-prompter_feedback" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation-prompter_feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"questionId" integer,
	"sessionId" integer,
	"feedback" text,
	"rating" integer,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "conversation-prompter_question" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation-prompter_question_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer,
	"question" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "conversation-prompter_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "conversation-prompter_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"theme" text,
	"customInstructions" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "conversation-prompter_feedback" ADD CONSTRAINT "conversation-prompter_feedback_questionId_conversation-prompter_question_id_fk" FOREIGN KEY ("questionId") REFERENCES "public"."conversation-prompter_question"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversation-prompter_feedback" ADD CONSTRAINT "conversation-prompter_feedback_sessionId_conversation-prompter_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."conversation-prompter_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "conversation-prompter_question" ADD CONSTRAINT "conversation-prompter_question_sessionId_conversation-prompter_session_id_fk" FOREIGN KEY ("sessionId") REFERENCES "public"."conversation-prompter_session"("id") ON DELETE no action ON UPDATE no action;